; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; TODO: Maybe we should use two separate PlatformIO projects set
; up like the following:
; workspace/
; ├── BusSniffer/
; │   ├── platformio.ini
; │   └── src/main.cpp
; └── CartEmulator/
;    ├── platformio.ini
;    └── src/main.cpp
[env:KaseyKinderbotCartBusSniffer]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 2000000
build_src_filter =
    +<sniffer/**>
    -<cartemulator/**>

[env:KaseyKinderbotCartEmulator]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 2000000
build_src_filter =
    -<sniffer/**>
    +<cartemulator/**>